#spring.application.name=SpringSecurity
server.port=8080

spring.datasource.url =jdbc:mysql://localhost:3306/ticket_store
spring.datasource.username=ticket_store
spring.datasource.password=ticket_store

spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect

